version: '3.8'

services: 
  devcontainer-example-workflow:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/work:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity